### ISSUE TITLE
hope you guys make a colab notebook to test this

### ISSUE THREAD

**Issue by GeorvityLabs** [LeeDongYeun/FixNoise#1]
great work @LeeDongYeun 
hope you can build a colab notebook , so that we could test the inference on colab gpu.

**Comment by LeeDongYeun** [comment]
It's been a long time, we finally add [colab notebook](https://colab.research.google.com/github/LeeDongYeun/FixNoise/blob/main/demo_colab.ipynb).

Additionally, you can open any jupyter notebook file by adding https://colab.research.google.com/ with a Github file link.
For example, https://colab.research.google.com/github/LeeDongYeun/FixNoise/blob/main/demo.ipynb
or
https://colab.research.google.com/github/LeeDongYeun/FixNoise/blob/main/demo_colab.ipynb

Thank you.
